image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test

deploy:
  stage: deploy
  script:
    - dotnet publish -c Release -o publish
  artifacts:
    paths:
      - publish